---
layout: cv
title: Emily McGovern Resume
---
# Emily McGovern
A motivated software engineering student proficient in Python, HTML, and CSS, with experience in JavaScript and C#. Passionate about creating efficient, user-friendly applications. Strong problem-solving, teamwork, and adaptability skills with experience in leadership and customer service.

<div id="ContactInfo">
<a href="mcg21013@byui.edu">mcg21013@byui.edu</a>
| <a href="https://www.linkedin.com/in/emily-irene-mcgovern/">My LinkedIn Page</a>
</div>


## Education

`Jan 2022 - Present`
__Brigham Young University - Idaho__

- Bachelor of Science in Software Engineering
- Awarded Academic Scholarship for maintaining a 3.9 GPA
- Member of the BYU-I Society of Women Engineers (SWE)

`Sept 2019 - June 2021`
__South Puget Sound Community College__

- High Honors
- GPA: 3.9



## Experience

`Mar 2025 - Aug 2025`
__Walt Disney World - College Internship: Attractions__

- Operated ride systems and ensured guest safety through strict operational procedures
- Delivered exceptional guest service in a fast-paced, high-volume environment
- Collaborated with team members to maintain ride efficiency and guest satisfaction
- Responded calmly and professionally to guest concerns, emergencies, and situations

`Aug 2022 - Dec 2024` `Sept 2025 - Dec 2025`
__Child and Youth Program Assistant__

- Designed and led engaging lessons for up to 8 infants ranging from 4 months to 18 months old, adapting to diverse learning styles
- Managed and resolved conflicts among children, fostering a positive learning environment
- Provided emotional support to families, assisting children during parental deployment
- Collaborated with a team of 2 to ensure a safe and nurturing environment for children




## Skills/Characteristic
- Technical Skills: Python, HTML, CSS, JavaScript, C#, C, Git, VS Code, GitHub, Microsoft Excel

- Soft Skills: Problem-solving, Teamwork, Team Leadership, Adaptability, Reliability, Time Management, Communication

## Projects

`July 2024`
__SRS Document: Show Starter__

- Utilized leadership skills by being reliable and compassionate to 24 team members
- Led a Technical Specialist team of 4 to define 25+ software requirements in Microsoft Word and Google Docs
- Facilitated conflict resolution and managing time constraints among a 24-member team


`July 2024`
__Travel Website to Colmar and Paris France__
- Developed an interactive travel website featuring 3 hotels, 3 restaurants, and 3 activities for visitors to France
- Implemented HTML, JavaScript, and CSS to enhance user experience and design.


<!-- ### Footer

Last updated: May 2013 -->